/**
 * Authoritative news-source allowlist (2026-05-13).
 *
 * Editorial policy from product owner: only entries from authoritative
 * publishers — official health agencies (WHO, ECDC, Swiss BAG, Taiwan
 * CDC, mainland NHC + China CDC, foreign ministries of health, …) and
 * Xinhua News Agency — should appear in the public 「最新通报」 feed.
 * Other mainland media (chinanews.com.cn, thepaper.cn, 天津日报, …) and
 * overseas commercial press (Reuters, BBC, NPR, …) are dropped as noise.
 *
 * Mirror of `NEWS_LEADS_AUTHORITATIVE_*` in
 * `services/collector/hantawatch_collector/news_leads.py`. Kept here so
 * the existing `recent-cases-intl.json` on disk (which was generated by
 * a pre-allowlist collector revision) is filtered at render time too —
 * we don't have to wait for the next bot run to see the cleanup.
 *
 * Scope:
 *   - Applied ONLY to `confidence: 'news'` entries.
 *   - `confidence: 'official'` (WHO DON / ECDC) and manual entries (ids
 *     starting with `manual-`) are exempt — those are authoritative by
 *     their collection path, not by outlet name.
 */

/** Substring patterns that, if found in the outlet name (case-insensitive),
 *  mark a lead as authoritative. Kept short — these are the rare "obvious"
 *  matches like Xinhua. */
const AUTHORITATIVE_OUTLETS: readonly string[] = [
  'xinhua',
  '新华',
];

/** Outlets that LOOK like they should match the allowlist (e.g. contain
 *  "新华") but are in fact provincial commercial press, not the central
 *  Xinhua News Agency. Checked BEFORE the allowlist so they win.
 *
 *  e.g. 新华报业网 = 江苏新华报业传媒集团 (provincial press group whose
 *  flagship is 新华日报). Editorial policy: only the central 新华社 /
 *  新华网 / Xinhua News Agency passes; provincial 新华-branded papers do
 *  not. */
const OUTLET_DENYLIST: readonly string[] = [
  '新华报业',          // 江苏新华报业传媒集团 / 新华报业网
  '新华日报',          // 江苏《新华日报》—— 省级党报
];

const HOST_DENYLIST: readonly string[] = [
  'xhby.net',          // 新华报业网 host
];

/** Longer-form patterns matching official health bodies across languages.
 *  Tuned for high precision — these phrases rarely appear in commercial
 *  media bylines, so substring matching is safe. */
const AUTHORITATIVE_OUTLET_PATTERNS: readonly string[] = [
  'world health organization',
  'ministry of health',
  'department of health',
  'centers for disease control',
  'centre for disease control',
  'european centre for disease',
  'ministerio de salud',          // most Latin American countries (ES)
  'ministère de la santé',        // FR
  'bundesamt für gesundheit',     // Swiss BAG long form (DE)
  '国家卫生健康委',                 // NHC mainland
  '卫生健康委员会',
  '疾病预防控制中心',               // 中国疾控中心
  '疾病管制',                      // 台湾省疾病管制署 (Taiwan CDC)
];

/** Host allowlist. An entry passes if its URL host equals one of these
 *  OR is a subdomain of one (e.g. `wjw.gd.gov.cn` matches `gov.cn`). */
const AUTHORITATIVE_HOSTS: readonly string[] = [
  // Mainland authoritative
  'news.cn',
  'xinhuanet.com',
  'gov.cn',
  'chinacdc.cn',
  // Foreign official health bodies
  'who.int',
  'ecdc.europa.eu',
  'bag.admin.ch',
  'cdc.gov.tw',
  'cdc.gov',
  'rki.de',
  'santepubliquefrance.fr',
  'canada.ca',
  'gov.uk',
  // Latin American health ministries (Andes serotype hot zone)
  'minsal.cl',
  'msal.gob.ar',
  'argentina.gob.ar',
  'salud.gob.mx',
  'minsa.gob.pe',
  'sanidad.gob.es',
];

function hostMatches(host: string, allowlist: readonly string[]): boolean {
  const h = host.toLowerCase().trim();
  if (!h) return false;
  return allowlist.some((allowed) => h === allowed || h.endsWith('.' + allowed));
}

/**
 * Decide whether a news-confidence entry should be visible.
 *
 * @param outletName  Human-readable source name (e.g. "新华网", "Reuters").
 * @param sourceUrl   The article URL. Used as a fallback when the outlet
 *                    name alone doesn't match — Google News sometimes
 *                    reports just a host, no friendly name.
 */
export function isAuthoritativeNewsSource(
  outletName: string | undefined | null,
  sourceUrl: string | undefined | null,
): boolean {
  const lc = (outletName || '').toLowerCase();
  let host = '';
  if (sourceUrl) {
    try {
      host = new URL(sourceUrl).hostname;
    } catch {
      // Malformed URL — host stays empty.
    }
  }

  // Denylist runs first — catches "新华XX" subsidiaries (e.g. 新华报业网)
  // that would otherwise sneak past the substring allowlist.
  if (OUTLET_DENYLIST.some((bad) => lc.includes(bad))) return false;
  if (host && hostMatches(host, HOST_DENYLIST)) return false;

  // Rule 1: short outlet matches (Xinhua family).
  if (AUTHORITATIVE_OUTLETS.some((needle) => lc.includes(needle))) return true;
  // Rule 2: long-form ministry / CDC patterns.
  if (AUTHORITATIVE_OUTLET_PATTERNS.some((pat) => lc.includes(pat))) return true;
  // Rule 3: URL host on allowlist.
  if (host && hostMatches(host, AUTHORITATIVE_HOSTS)) return true;
  return false;
}
